export const TencentCloudRegionList: Record<string, string> = {
    "ap-beijing": "China (Beijing)",
    "ap-nanjing": "China (Nanjing)",
    "ap-shanghai": "China (Shanghai)",
    "ap-guangzhou": "China (Guangzhou)",
    "ap-chengdu": "China (Chengdu)",
    "ap-chongqing": "China (Chongqing)",
    "ap-hongkong": "China (Hong Kong)",
    "ap-singapore": "Singapore",
    "ap-mumbai": "Mumbai",
    "ap-jakarta": "Jakarta",
    "ap-seoul": "Seoul",
    "ap-bangkok": "Bangkok",
    "ap-tokyo": "Tokyo",
    "na-siliconvalley": "North America (Silicon Valley - West US)",
    "na-ashburn": "North America (Virginia - East US)",
    "sa-saopaulo": "South America (São Paulo)",
    "eu-frankfurt": "Europe (Frankfurt)",
}